- name: gitlab | common
  remote_user: centos
  hosts: gitlab
  roles:
    - common
    - firewalld
  tags:
    - common


- name: gitlab | docker-ce
  remote_user: centos
  hosts: gitlab
  roles:
    - docker-ce
  tags:
    - docker-ce
